{{- if .Values.services.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stock.fullname" . }}-postgresql
  labels:
    {{- include "stock.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.services.postgresql.secret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if .Values.services.postgresql.enablePrometheusMetrics }}
  DATA_SOURCE_USER: exporter
  DATA_SOURCE_PASS: {{ randAlphaNum 16 | quote }}
  {{- end }}
  POSTGRES_N8N_USER: {{ required "A valid n8nMain.secret.DB_POSTGRESDB_USER environment variable required!" .Values.services.n8nMain.secret.POSTGRES_USER | quote }}
  POSTGRES_N8N_SCHEMA: {{ required "A valid n8nMain.secret.DB_POSTGRESDB_SCHEMA environment variable required!" .Values.services.n8nMain.secret.POSTGRES_DB | quote }}
  POSTGRES_N8N_PASSWORD: {{ required "A valid n8nMain.secret.DB_POSTGRESDB_PASSWORD environment variable required!" .Values.services.n8nMain.secret.POSTGRES_PASSWORD | quote }}
{{- end }}