apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stock.fullname" . }}-n8n-worker
  labels:
    {{- include "stock.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.services.n8nWorker.secret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- $defaultPgHost := printf "postgresql-0.%s-postgresql.%s.svc.cluster.local" (include "stock.fullname" .) .Release.Namespace }}
  {{- $defaultRedisHost := printf "redis-0.%s-redis.%s.svc.cluster.local" (include "stock.fullname" .) .Release.Namespace }}
  {{- if .Values.services.postgresql.enabled }}
  DB_POSTGRESDB_HOST: {{ .Values.services.n8nWorker.secret.DB_POSTGRESDB_HOST | default $defaultPgHost }}
  {{- end }}
  {{- if .Values.services.redis.enabled }}
  QUEUE_BULL_REDIS_HOST: {{ .Values.services.n8nWorker.secret.QUEUE_BULL_REDIS_HOST | default $defaultRedisHost }}
  {{- end }}