apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stock.fullname" . }}-n8n-main
  labels:
    {{- include "stock.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.services.n8nMain.secret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- $defaultPgHost := printf "postgresql-0.%s-postgresql.%s.svc.cluster.local" (include "stock.fullname" .) .Release.Namespace }}
  {{- $defaultRedisHost := printf "redis-0.%s-redis.%s.svc.cluster.local" (include "stock.fullname" .) .Release.Namespace }}
  {{- if .Values.services.postgresql.enabled }}
  DB_POSTGRESDB_HOST: {{ .Values.services.n8nMain.secret.DB_POSTGRESDB_HOST | default $defaultPgHost }}
  {{- end }}
  {{- if .Values.services.redis.enabled }}
  QUEUE_BULL_REDIS_HOST: {{ .Values.services.n8nMain.secret.QUEUE_BULL_REDIS_HOST | default $defaultRedisHost }}
  {{- end }}
  {{- if .Values.services.n8nMain.job.migration.enabled }}
  {{- if .Values.services.n8nMain.job.migration.targetDatabase.useLocalDatabase }}
  LIQUIBASE_URL: {{ printf "jdbc:postgresql://%s:%s/%s?currentSchema=%s" $defaultPgHost (.Values.services.postgresql.containerPort | toString) .Values.services.postgresql.env.POSTGRES_DB .Values.services.n8nMain.job.migration.targetDatabase.schema }}
  {{- else }}
  LIQUIBASE_URL: {{ printf "jdbc:%s://%s:%s/%s?currentSchema=%s" .Values.services.n8nMain.job.migration.targetDatabase.type .Values.services.n8nMain.job.migration.targetDatabase.host (.Values.services.n8nMain.job.migration.targetDatabase.port | toString) .Values.services.n8nMain.job.migration.targetDatabase.database .Values.services.n8nMain.job.migration.targetDatabase.schema }}
  {{- end }}
  LIQUIBASE_USERNAME: {{ .Values.services.n8nMain.job.migration.targetDatabase.user }}
  LIQUIBASE_PASSWORD: {{ .Values.services.n8nMain.job.migration.targetDatabase.password }}
  {{- end }}