{{- if .Values.services.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stock.fullname" . }}-redis
  labels:
    {{- include "stock.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.services.redis.secret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}